export interface InsuranceDetail {
  phname: string
  phemail: string
  phcontactno: string
  phaddress: string
  phstate: string
  phcity: string
  phpincode: string
  phdob: string
  invno: string
  invdate: string
  invval: string
  invdoc: string
  purstore: string
  polcomp: string
  polno: string
  polstart: string
  polend: string
  polstatus: string
  poldoc?: string
  rendate: string
  requestno: string
  polfile?: string
  invfile: string
  remarks: string
  createdat: string
  current_price: string
  uid: string
  id?: number
}
