export { default as callWebService } from './web-service'
export * from './endpoints'
export { default as login } from './login'
export * from './insurance-detail'
export * from './resale-detail'
export * from './user-detail'
export * from './special-products-detail'
export * from './store-locator'
export * from './store-locator-detail'
export * from './premium-chart'
export * from './exchange-rate-detail'
//select * from './dashboard-detail'
