name: Staging
on:
  push:
    branches: [ master ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Staging
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "*"
          target: "/var/www/html/admin/divine-solitaire-frontend"
