name: Node.js CI/CD

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: test # this job depends on "test" having finished
    #if: github.ref ‘refs/heads/master' # we tell Github to only execute this step if we're on our master branch (so we don't put unfinished branches in production)

    strategy:
      fail-fast: false # tells github to not run further steps if this one fails
      matrix:
        node-version: [16.x] # sets the version of node we want to use, should be what you have on your server 
    steps:
      - name: Deploying to Divine Server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          #port: ${{ secrets.PORT }}

          script: |
            cd ${{ secrets.WORK_DIR }} # we move into our app's folder
            forever stop 1
            git pull # we pull any changes from git
            export NVM _DIR=~/.nvm #get the nvm envirorment to run npm commands
            source ~/.nvm/nvm.sh
            npx pnpm install # we install any missing dependencies
            npx pnpm build # we build our app
            forever start -c "npx pnpm start" ./
